version: "3.9"
services:
  backend:
    build:
      context: ./backend
      args:
        SUMMARIZER_MODEL: facebook/bart-large-cnn
        WHISPER_MODEL: tiny
    container_name: yt-backend
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/models_cache
      - TRANSFORMERS_CACHE=/models_cache
      - TORCH_HOME=/models_cache
      - API_BASE=http://localhost:8000
    restart: unless-stopped
    volumes:
      - ./backend/app/data:/app/app/data       
      - ./cookies.txt:/app/cookies.txt         

  frontend:
    build: ./frontend
    container_name: yt-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
